services:
  - type: web
    name: farmguardian
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 5000
      - key: OMNIDIMENSION_API_KEY
        value: 0YkbCjLJc-LSJShpxCd32o3_F9lBlaAwhrlpzmZMYoQ
      - key: OPENWEATHER_API_KEY
        value: ae40227be61af3c1fbc5a468e2f8b295
